### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by nikitalita** [svenmeier/jorgan#1]
I'm not really certain how to build this; `./build.sh` fails on Ubuntu 20.04 with JDK 11 and 15 with complaints of no `jni.h`. What are the build requirements?

**Comment by svenmeier** [comment]
Could you attach your command line output?

**Comment by nikitalita** [comment]
[jorgan-build.log](https://github.com/svenmeier/jorgan/files/6357828/jorgan-build.log)

so to be clear, I'm running `ant` to build all the packages, and it fails on packages that have native dependencies and require `jni.h`. `run.sh` runs ok, but naturally none of the functionality (like fluidsynth) that require those packages works.

**Comment by nikitalita** [comment]
Ah hah, I see the issue: I use sdkman to manage my java SDKs, and this uses the path `/usr/lib/jvm/default-java`, which would use the system's installed JDK. I only had the JRE installed. Installing the ubuntu provided JDK made it work, and changing `unix.jdk` to use my `sdkman` JDK installation also worked. Perhaps using `JAVA_HOME` would be better here?

**Comment by svenmeier** [comment]
JAVA_HOME isn't set on my machine ;)

I've changed the properties to point to the include directory and give a better error message.
