### ISSUE TITLE
Intercepting MIDI signals coming from a Switch Filter by another Switch Filter

### ISSUE THREAD

**Issue by davy7125** [svenmeier/jorgan#8]
(This is more a question than an issue but I cannot find the "nabble" forum anymore. I highly suggest opening another one since mastering all capabilities of jOrgan is really tight)

# Context

With jOrgan I'm using three series of switch filters, each series sending values for a different CC (for example CC20, CC21 and CC22).
```
Engaged: set 176, set 20, set XXX (first switch filter)
Engaged: set 176, set 21, set YYY (second switch filter)
Engaged: set 176, set 22, set ZZZ (third switch filter)
```

These switch filters are linked to ranks and I'm using modulators in a soundfont that listen to these CC values for changing the tuning.
My goal is to multiply XXX by YYY by ZZZ before changing the tuning of a soundfont preset and this could be achieved using linked modulators: a first modulator multiplies XXX by YYY and sends the result to another modulator that multiplies it by ZZZ and sends the new result to the fine tuning. The theory is OK.

# Problem

But... linked modulators are not implemented yet in FluidSynth and thus only one multiplication is allowed. That's why I'd like to multiply XXX by YYY within jOrgan before sending the result to the soundfont.

After the reading of these pages:
* https://jorgan.info/base/Midi.html
* https://jorgan.info/base/c/Continuous_filter.html
* https://jorgan.info/base/s/Switch_filter.html

My first attempt was to intercept values of CC20 (XXX) and CC21 (YYY) in a switch or a continuous filter, before sending the result as a new CC (number 23).
```
Intercept: equal 176, equal 20, get valA
Intercept: equal 176, equal 21, get valB
Engaged: set 176, set 23, set valA | mult valB
```
This way, in a soundfont I would just need to multiply CC22 (ZZZ) by CC23 (containing the result of XXX * YYY).
But the CC values don't seem to be intercepted by the switch or continuous filter.

The other solution I thought but that is not allowed is to intercept messages in a rank.

# Question

How would it be possible in jOrgan to intercept CC values, multiply them and then send the result to a specific MIDI CC?

**Comment by svenmeier** [comment]
You can ask questions on our mailing list: https://sourceforge.net/p/jorgan/mailman/

On first sight you solution should work - is the additional switch filter (with the intercept messages) actually set to active? Otherwise it will send out the Disengaged message (which does not seems to be present).

**Comment by davy7125** [comment]
Found it! I had to pay attention to the order of the switch filters. The switch filter that intercepts messages must be placed first in the "references to" of a rank, then the switch filters modifying messages.
